typography_spectrum: 0.79111
color:
  brandColors:
    - '#83d6fb'
    - '#ffffff'
    - '#181816'
    - '#7b7c77'
    - '#acad9d'
  brandStrength: 0.5
  lightness: 0.25
  saturation: 1
  rhythmicContrast: 0.5
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 1
analytics:
  google: null
  facebook: null
  twitter: null
name: ƒonchi
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Mi ojos
    url: 'http://yamegusta.tumblr.com/'
    type: external
favicon: null
title: As iF
purpose: []
