name: fonchi
favicon: null
layout_spectrum: 0.39982200181111693
typography_spectrum: 0.7890469995327294
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#83d6fb'
    - '#ffffff'
    - '#181816'
    - '#7b7c77'
    - '#acad9d'
  brandStrength: 0.5
  lightness: 0.25
  saturation: 1
  rhythmicContrast: 0.5
purpose: []
